# Generated by Django 3.1.7 on 2021-03-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210326_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='upload',
            field=models.ImageField(upload_to='media'),
        ),
    ]
