# Generated by Django 3.1.7 on 2021-03-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210329_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Descrição da Foto'),
        ),
    ]
