# Generated by Django 3.1.7 on 2021-03-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210329_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='upload',
            field=models.ImageField(null=True, upload_to='', verbose_name='Upload'),
        ),
    ]
