# Generated by Django 3.1.7 on 2021-04-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_photo_aprovado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='aprovado',
        ),
        migrations.AddField(
            model_name='photo',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Status'),
        ),
    ]
